# -*- coding: utf-8 -*-
"""Assignment-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lMfDrToRO4DCjTgb6M1O_VOnqDG6wiio
"""

# importing the required modules
import matplotlib.pyplot as plt
import numpy as np

#defining f(x)
def f(x):
  if(x<0):
    return 0
  elif(x>=0) and (x<1/2):
    return x**2
  elif(x>=1/2) and (x<1):
    return 3/4
  elif(x>=1):
    return 1;
  else:
    return 0  

#setting the X co-ordinate
X = np.linspace(-1.5,1,100000)

#setting the Y co-ordinate
Y = [f(x) for x in X]

plt.xlabel('X=x')
plt.ylabel('y= F(x)')
plt.plot(X,Y)
plt.title('Cummulative Distribution Function for X ')
plt.show()

