# -*- coding: utf-8 -*-
"""assignment6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QyJ5nB37eAG97-Oowv4VDELXRwGHv3u_
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import bernoulli
import math
from scipy import stats
from scipy import integrate
import random
import decimal
count=0


num_sim=10000000
for i in range(num_sim):
  x=random.uniform(0,10)
  y=random.uniform(0,20)
  if x+y >20 :
    count+=1
prob=count/num_sim
print(f'probability that (x+y)>20 =',prob)