# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rdpHToOdavVEF66hUU5FpyUOuYgJIdH_
"""

import math
from scipy.stats import binom
import matplotlib.pyplot as plt
import array as arr
import numpy as np
import random

x = np.linspace(0, 100, 100) 
fig = plt.figure() 
plt.plot(x, np.exp(-x)) 
plt.xlabel("Value of t")
plt.ylabel("Probability density function f(t)")
plt.show()