# -*- coding: utf-8 -*-
"""poisson.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15g7sOn5TP68hgUl6RvuHTRIVRvwhFEZ8
"""

from scipy.stats import poisson
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sn
import xlrd
import scipy as sp
import math

_lambda=7
simlen=100000

r=poisson.rvs(_lambda,size=simlen)

sim_pmf=[]

for k in range(0,16):
  sim_pmf.append(poisson.pmf(k,_lambda))

X = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

plt.xlim([0,15])
plt.ylim([0,1])
plt.title('Probability Mass Distribution')
plt.xlabel('k')
plt.ylabel('P(X=k)')
markerline, stemlines, baseline = plt.stem(X,sim_pmf, '-')
plt.show()