# -*- coding: utf-8 -*-
"""Asignt2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LzLhwi8z5XKA-P5VD-YDgR0evOX6KhCi
"""

# for the given f(x,y)=2 for 0<x+y<1
#To find the P(x+y<1/2) = integral of integral of  [ f(x,y)] dx dy
#we are calculating a small volume around a random point and 
#and adding the volumes at desired points  


import numpy as np
from matplotlib import pyplot as plt
#sample space
n=1000

#array of x coordinate points
x=np.linspace(0,1,1000)

#array of y coordinate points
y=np.linspace(0,1,1000)


#intilisation of count of  P(x+y< 1/2) = P
P=0

#small volume  dx * dy * f(x,y)
volume=0.001*0.001*2


 
for i in range(n):
  for j in range(n):
    if(x[i]+y[j]<(1/2)):
      P=P+volume


print("simulated P(x+y<(1/2)) is ",P)
print("theoritical P(x+y<1/2) is ", 1/4)
print("with neglegible error we can conclude P(x+y<1/2) is ",1/4)