# -*- coding: utf-8 -*-
"""Assignment_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v_oAC0AvbEDmLVNrXBHMSWp6Agvimw5f
"""

import numpy as np
from matplotlib import pyplot as plt
from scipy.stats import bernoulli

#For plotting the CDF of X
#Setting the corresponding x and y co-ordinates

#Region 1 of CDF
x_1 = np.linspace(0,5,100)
y_1 = 1-(np.exp(-3*x_1)/2)
#Region 2 of CDF
x_2 = np.linspace(-5,0,100)
y_2 = np.exp(4*x_2)/2

#Plotting the points
plt.plot(x_1,y_1,'b')
plt.plot(x_2,y_2,'b')
plt.xlabel('Random Variable,X')
plt.ylabel('$F_X(x)$')
plt.grid()
plt.show()

#For plotting the PDF of X
#Setting the corresponding x and y co-ordinates 

#Region 1 of PDF
x_1 = np.linspace(0,5,100)
y_1 = (3*np.exp(-3*x_1))/2
#Region 2 of PDF
x_2 = np.linspace(-5,0,100)
y_2 = 2*np.exp(4*x_2)

#Plotting the points
plt.plot(x_1,y_1,'b')
plt.plot(x_2,y_2,'b')
plt.xlabel('Random Variable,X')
plt.ylabel('$f_x(x)$')
plt.grid()
plt.show()